### ISSUE TITLE
python3 ImportError: dynamic module does not define module export function (PyInit__tf2) 

### ISSUE THREAD

**Issue by zhengshuai1** [ethz-asl/vgn#5] opened 2021-01-19 07:36 UTC
Hi, My hardware environment is: ubuntu 18.04 and ros melodic, python 3 virtual environment.
When I run the robot grasping: python scripts/panda_grasp.py --model data/models/vgn_conv.pth
the error is:
Traceback (most recent call last):
  File "scripts/panda_grasp.py", line 17, in <module>
    from vgn import vis
  File "/home/hp/graspdemo_ws/src/vgn/src/vgn/vis.py", line 10, in <module>
    from vgn.utils import ros_utils, workspace_lines
  File "/home/hp/graspdemo_ws/src/vgn/src/vgn/utils/ros_utils.py", line 6, in <module>
    import tf2_ros
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define module export function (PyInit__tf2)

I search this error on the website, it shows that I should use python2 rather than python3 to run this .py script. However, when I use python2 I can't use pip to install the black module in the requirements. How could I solve this problem?

**Comment by maxsvetlik** [comment] 2021-02-09 22:21
Am experiencing this same thing (18.04, Python 2.7 base, running this VGN in a Python 3.6 virtual environment). I didn't want to migrate to Noetic, in which the above error wouldn't come up because MoveIt and its dependent ROS packages would all be compiled against Python 3 (resolving the issue the error is complaining about)

My workaround has been this: comment out the `vis` lines that are problematic, as well as moveit_commander in `panda_control.py` and port the code in `panda_control.py` that uses moveit_commander directly to using the topics that MoveIt exposes, namely the `/move_group/goal` action.
This obviously isn't ideal if you need visualization, but as far as robot control it's equivalent. 

My _real_ suggestion would be to run `vgn` in a docker container that is running 20.04 / Noetic; this would have been my first preference but doesn't exactly solve all my issues, thus I went with the above workaround.

**Comment by mbreyer** [comment] 2021-02-11 10:19
Hi, the issue is that I upgraded my system to Ubuntu 20.04 for python3 support, but I realize now that some dependencies are just not ready for ROS noetic yet. I'll have a look at making the package compatible with both python versions :slightly_smiling_face:

**Closed as completed** 2021-02-12 09:15 UTC

**Comment by fatPeter** [comment] 2022-10-20 08:44
A pausible solution for me. 
https://blog.csdn.net/jiesunliu3215/article/details/124365080
